#!/usr/bin/env python3
"""Generate the caster from audited CAD poses and configurable mass assumptions.

Needs numpy, scipy and PyYAML only. CAD parsing is a separate optional step.
No fitted spheres replace the hemispheres: their pole holes, band/cap phases,
20 mm central gap and actual saved tessellation are retained.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import xml.etree.ElementTree as ET

import numpy as np
from scipy.spatial.transform import Rotation
import yaml

PACKAGE = Path(__file__).resolve().parents[1]
NS = "http://www.ros.org/wiki/xacro"
ET.register_namespace("xacro", NS)
# Native caster fork -Z is up. This agrees with the whole-robot CAD convention
# ROS x=-CADglobalZ, y=-CADglobalX, z=CADglobalY at its nominal level pose.
Q = np.array([[0., -1., 0.], [-1., 0., 0.], [0., 0., -1.]])
GROUP_NAMES = {
    "fork": "fork", "carrier": "carrier",
    "positive_shell": "positive_hemisphere",
    "negative_shell": "negative_hemisphere",
    "positive_polar_roller": "positive_polar_roller",
    "negative_polar_roller": "negative_polar_roller",
}
COLLISION_PARTS = {
    "semi_spherical_wheel", "semi_spherical_wheel_2", "roller",
    "caster_fork", "ball_caster_shaft_2", "bearing_shaft2",
    "collet_block", "roller_mount", "roller_shaft",
}


def fmt(x):
    return f"{float(x):.14g}"


def vec(v):
    return " ".join(fmt(x) for x in v)


def origin(node, xyz, R=None):
    attrs = {"xyz": vec(xyz)}
    if R is not None:
        attrs["rpy"] = vec(Rotation.from_matrix(R).as_euler("xyz"))
    return ET.SubElement(node, "origin", attrs)


def mass_properties(items, centers, parts, config):
    output = {}
    for group in GROUP_NAMES:
        components = []
        for inst in items:
            if inst["group"] != group:
                continue
            key = inst["part_key"]
            p = parts[key]["unit_density_properties"]
            physical = config["parts"][key]
            volume = float(p["volume_m3"])
            mass = float(physical["mass_kg"] if "mass_kg" in physical
                         else volume * physical["density_kg_m3"])
            if not np.isfinite(mass) or mass <= 0:
                raise ValueError(f"{key}: mass must be finite and positive")
            T = np.asarray(inst["transform"], dtype=float)
            R = Q @ T[:3, :3]
            com = Q @ (T[:3, :3] @ p["center_of_mass_m"] + T[:3, 3]) - centers[group]
            inertia = R @ np.asarray(p["inertia_at_com_m5"]) @ R.T * (mass / volume)
            components.append((mass, com, inertia, inst["key"]))
        total = sum(c[0] for c in components)
        com = sum(m * c for m, c, _, _ in components) / total
        inertia = np.zeros((3, 3))
        for m, c, I, _ in components:
            d = c - com
            inertia += I + m * (np.dot(d, d) * np.eye(3) - np.outer(d, d))
        eig = np.linalg.eigvalsh(inertia)
        if eig[0] <= 0 or eig[-1] > eig[0] + eig[1] + 1e-10:
            raise ValueError(f"Nonphysical inertia in {group}: {eig}")
        output[group] = {
            "mass_kg": total, "com_m": com.tolist(),
            "inertia_at_com_kg_m2": inertia.tolist(),
            "inertia_eigenvalues_kg_m2": eig.tolist(),
            "components": [c[3] for c in components],
        }
    return output


def build(package=PACKAGE):
    extraction = json.loads((package / "assets/provenance/extraction.json").read_text())
    assembly = json.loads((package / "assets/provenance/assembly.json").read_text())
    config_path = package / "config/physical_properties.yaml"
    config = yaml.safe_load(config_path.read_text())
    occurrences = assembly["occurrences"]
    parts = extraction["parts"]
    joints = assembly["joint_axes"]
    centers = {name: np.zeros(3) for name in GROUP_NAMES}
    for name in ("positive_polar_roller", "negative_polar_roller"):
        centers[name] = Q @ np.asarray(joints[name]["origin"])
    props = mass_properties(occurrences, centers, parts, config)

    root = ET.Element("robot", {"name": "cad_split_ball_caster"})
    root.append(ET.Comment(" GENERATED by tools/generate_model.py; edit config/provenance, not mesh poses. SI units. "))
    macro = ET.SubElement(root, f"{{{NS}}}macro", {
        "name": "ball_caster",
        "params": "prefix parent center_xyz:='0 0 0' center_rpy:='0 0 0' mass_scale:=1.0 carrier_phase:=0.0",
    })
    names = {k: "${prefix}" + v + "_link" for k, v in GROUP_NAMES.items()}
    for group, name in names.items():
        link = ET.SubElement(macro, "link", {"name": name})
        p = props[group]
        inertial = ET.SubElement(link, "inertial")
        origin(inertial, p["com_m"])
        ET.SubElement(inertial, "mass", {"value": "${mass_scale * " + fmt(p["mass_kg"]) + "}"})
        I = np.array(p["inertia_at_com_kg_m2"])
        ET.SubElement(inertial, "inertia", {
            key: "${mass_scale * " + fmt(I[i, j]) + "}"
            for key, i, j in (("ixx", 0, 0), ("ixy", 0, 1), ("ixz", 0, 2),
                              ("iyy", 1, 1), ("iyz", 1, 2), ("izz", 2, 2))
        })
        for inst in occurrences:
            if inst["group"] != group:
                continue
            part = parts[inst["part_key"]]
            T = np.asarray(inst["transform"])
            xyz = Q @ T[:3, 3] - centers[group]
            R = Q @ T[:3, :3]
            visual = ET.SubElement(link, "visual", {"name": "${prefix}" + inst["key"] + "_visual"})
            origin(visual, xyz, R)
            geom = ET.SubElement(visual, "geometry")
            ET.SubElement(geom, "mesh", {"filename": "package://hamr_ball_caster/" + part["mesh_file"]})
            color = {"positive_shell": "0.16 0.46 0.85 1", "negative_shell": "0.92 0.46 0.12 1",
                     "positive_polar_roller": "0.13 0.13 0.13 1", "negative_polar_roller": "0.13 0.13 0.13 1",
                     "carrier": "0.55 0.57 0.60 1", "fork": "0.7 0.72 0.74 1"}[group]
            mat = ET.SubElement(visual, "material", {"name": "${prefix}" + group + "_material"})
            ET.SubElement(mat, "color", {"rgba": color})
            if inst["part_key"] in COLLISION_PARTS:
                collision = ET.SubElement(link, "collision", {"name": "${prefix}" + inst["key"] + "_collision"})
                origin(collision, xyz, R)
                geom = ET.SubElement(collision, "geometry")
                ET.SubElement(geom, "mesh", {"filename": "package://hamr_ball_caster/" + part["mesh_file"]})
        gz = ET.SubElement(macro, "gazebo", {"reference": name})
        ET.SubElement(gz, "selfCollide").text = "false"
        ET.SubElement(gz, "mu1").text = str(config["contact"]["mesh_nominal_mu"])
        ET.SubElement(gz, "mu2").text = str(config["contact"]["mesh_nominal_mu"])

    mounting = ET.SubElement(macro, "joint", {"name": "${prefix}mount_joint", "type": "fixed"})
    ET.SubElement(mounting, "parent", {"link": "${parent}"})
    ET.SubElement(mounting, "child", {"link": names["fork"]})
    ET.SubElement(mounting, "origin", {"xyz": "${center_xyz}", "rpy": "${center_rpy}"})
    # Keep the complete fork as a distinct body/frame during URDF->SDF conversion.
    gz = ET.SubElement(macro, "gazebo", {"reference": "${prefix}mount_joint"})
    ET.SubElement(gz, "preserveFixedJoint").text = "true"
    for group, joint in joints.items():
        if group not in GROUP_NAMES or group == "fork":
            continue
        parent = "fork" if group == "carrier" else "carrier"
        jname = "${prefix}" + GROUP_NAMES[group] + "_joint"
        j = ET.SubElement(macro, "joint", {"name": jname, "type": "continuous"})
        ET.SubElement(j, "parent", {"link": names[parent]})
        ET.SubElement(j, "child", {"link": names[group]})
        jo = origin(j, centers[group] - centers[parent])
        if group == "carrier":
            jo.set("rpy", "0 ${-carrier_phase} 0")
        ET.SubElement(j, "axis", {"xyz": vec(Q @ np.asarray(joint["axis"]))})
        ET.SubElement(j, "limit", {"effort": "100", "velocity": "1000"})
        dyn = config["joints"][group]
        ET.SubElement(j, "dynamics", {"damping": str(dyn["damping_Nm_s_per_rad"]), "friction": str(dyn["friction_Nm"])})

    out = package / "urdf/ball_caster.xacro"
    out.parent.mkdir(parents=True, exist_ok=True)
    ET.indent(root, space="  ")
    ET.ElementTree(root).write(out, encoding="utf-8", xml_declaration=True)
    model_info = {
        "canonical_rotation_from_native": Q.tolist(), "link_origin_in_canonical_m": {k: v.tolist() for k, v in centers.items()},
        "mass_properties": props, "total_caster_mass_kg": sum(p["mass_kg"] for p in props.values()),
        "config_sha256": hashlib.sha256(config_path.read_bytes()).hexdigest(),
        "collision_parts": sorted(COLLISION_PARTS),
        "caveat": "Nominal densities and ideal bearing joints. Native CAD saved tessellation, not validated manufactured dynamics.",
    }
    (package / "assets/provenance/model_properties.json").write_text(json.dumps(model_info, indent=2) + "\n")
    print(f"Generated {out}; nominal caster mass {model_info['total_caster_mass_kg']:.6f} kg")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--package", type=Path, default=PACKAGE)
    build(parser.parse_args().package)
